# Numpy n-dimensionale Arrays

In [3]:
import numpy as np

Numpy kann mehrdimensionaleArrays erstellen. Dieses Dokument erläutert den Aufbau  undden Datenzugang.

### 1D Array
Der 1D Array ist eine Aneinanderreihung von Zahlenwerten, die zwischen die "[ ]" geschrieben werden. Diese werden durch ein "," getrennt

In [5]:
OneDArray = np.array([2,3])
OneDArray

array([2, 3])

Die Werte können über ihre Position innerhalb der "[ ]" abgerufen werden. Die erste Position ist mit 0 indexiert.

In [6]:
OneDArray[1]

3

### 2D Arrays
Die 2D Arrays setzten sich aus zwei 1D Arrays zusammen, welche hintereinander durch ein ", getrennt wiederum in "[ ]" gesetzt werden.  

In [7]:
TwoDArray = np.array([[2,3],[4,5]])
TwoDArray

array([[2, 3],
       [4, 5]])

Die Werte müssen über ein zweistelliges Argument innerhalb der "[ ]" abgefragt werden. Diese Argumente werden wiederum mit einem "," getrennt, so dass eine Abfrage wie folg aussieht: [x,y]

Das erste Element fragt die Reihe ab, das zweite die Spalte.[row,column]

Wollen wir also die Nummer 4 abfragen wird das wie folgt gemacht (behalte im Hinterkopf, das die 0 die erste Stelle indexiert):

In [8]:
TwoDArray[1,0]

4

### 3D Arrays
Die 3D Arrays sind wiederum aus zwei 2D Arrays zusammengesetzt. Der Aufbau gleicht dem des vorhergehenden Schrittes, nur dass wir jetzt eine weitere Verschachtelung haben. Zur Veranschaulichung kann man sich zwei 2DTabellen vorstellen, die hintereinander angeordnet sind.

1D: [1D,1D]

2D: [2D,2D] ist das gleiche wie [[1D,1D],[1D,1D]]

3D: [3D,3D] ist das gleiche wie [[2D,2D],[2D,2D]] ist das gleiche wie [[[1D,1D],[1D,1D]],[[1D,1D],[1D,1D]]]

In [9]:
ThreeDArray = np.array([[[2,3],[4,5]],[[6,7],[8,9]]])
ThreeDArray

array([[[2, 3],
        [4, 5]],

       [[6, 7],
        [8, 9]]])

Der Zugriff ist etwas schlechter zu veranschaulichen. Am besten stellt man sich einen Würfel vor, der - wie im Beispiel - aus zwei Ebenen beseteht. Jede dieser beiden Ebenen besteht wiederum aus vier Elementen. Oder um es kürzer zu sagen, ein Würfel, der aus acht gleich großen kleineren Würfeln besteht.

Die Abfrage ist wiederum ein dreiteiliges Element, innerhalb "[ ]", getrennt von ",".

Das erste Element steuert den Zugriff auf die zwei 3D Elemente. Das zweite Element steuert den Zugriff auf die Reihen innerhalb beider 3D Elemente und das dritte den Zugriff auf die Spalten innerhalb der beiden 3D Elemente. Das sieht wie folgt aus:

In [11]:
#Frage das erste 3D Elemenet ab in der Struktur [3D,3D]
#da der 3D Array aus einem 2-5 und einem 6-9 Element besteht fragen wir mit "0" das erste dieser Elemente ab
ThreeDArray[0,:,:]

array([[2, 3],
       [4, 5]])

In [12]:
#wollen wir nach der Reihe abfragen, gibt die Abfrage von beiden 3D Elementen die angefragte Reihe wieder
#dies ist so, da für die Trennung nach 3D Würfel das erstel Element der Abfrage zuständig ist
ThreeDArray[:,0,:]

array([[2, 3],
       [6, 7]])

In [13]:
#wir können aber natürlich auch nur die erste Reihe des ersten 3D Elements abfragen
#dies machen wir indem wir die beiden Abfragen kombinieren
ThreeDArray[0,0,:]

array([2, 3])

In [14]:
#Wollen wir die Spalten läuft das über das letzte Element ab (Spalten von beiden 3D Elementen)
ThreeDArray[:,:,0]

array([[2, 4],
       [6, 8]])

In [19]:
#wollen wir also die 5 machen wir das wie folgt
print("Alle Elemente:")
print(ThreeDArray)
print("Wählen des Würfels:")
print(ThreeDArray[0,:,:])
print("Wählen der Reihe:")
print(ThreeDArray[0,1,:])
print("Wählen der Spalte:")
print(ThreeDArray[0,1,1])
print("Tada!!")

Alle Elemente:
[[[2 3]
  [4 5]]

 [[6 7]
  [8 9]]]
Wählen des Würfels:
[[2 3]
 [4 5]]
Wählen der Reihe:
[4 5]
Wählen der Spalte:
5
Tada!!
